# Generated by Django 5.1.6 on 2025-06-01 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_sensitivities', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker_symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('custom_sensitivities', models.JSONField(blank=True, default=list)),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata_analysis.assettype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_analysis.company')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('matched_assets', models.ManyToManyField(to='metadata_analysis.asset')),
            ],
        ),
        migrations.CreateModel(
            name='StockImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_impact', models.CharField(choices=[('positive', '📈 Positive'), ('neutral', '⚪ Neutral'), ('negative', '📉 Negative')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_analysis.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_analysis.event')),
            ],
        ),
    ]
